### PR TITLE
schematic: Fix compilation errors triggered when built with g++.

### PR DESCRIPTION
**Pull request by vzh**
The issue has been introduced in commit ec09490.

### CODE REVIEW

**Comment by graahnul-grom** [comment]
Also noticed that compilation with `clang++` 8.0.0 gives the following warnings:
1) `gschem_object_properties_widget.c:671`:
```
result of comparison of constant -1 with expression of type 'OBJECT_END' (aka '_GedaLineCapType') is always true [-Wtautological-constant-out-of-range-compare]
```
2) `gschem_object_properties_widget.c:802`:
```
result of comparison of constant -1 with expression of type 'OBJECT_TYPE' (aka '_GedaLineType') is always true [-Wtautological-constant-out-of-range-compare]
```

**Comment by vzh** [comment]
@graahnul-grom, I think you know what to do with those warnings ;-)
