### PR TITLE
cli: Fix compilation errors by g++ in export_list_paper_size_names().

### PR DESCRIPTION
**Pull request by vzh**
Introduced in commit 23063d4220.

Affects #486.

### CODE REVIEW

**Comment by vzh** [comment]
Never mind :-)
